spring:
  application:
    name: course-management
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:courseapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  security:
    filter:
      order: 10

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: "never"
    info:
      enabled: true

server:
  error:
    include-stacktrace: NEVER
  forward-headers-strategy: framework

app:
  plugin:
    url:
  security:
    cors:
      allowed-origins: "http://localhost:8080"
    rate-limit:
      login-attempts: 5
      lockout-time-minutes: 15

logging:
  level:
    ru.mtuci.coursemanagement: INFO
    org.springframework.security: WARN