name: SCA CI

on:
  pull_request:
    branches:
      - main

jobs:
  sca:
    name: OWASP
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.10-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Run Maven verify with OWASP Dependency-Check
        run: ./mvnw -B verify

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
